# Generated by Django 2.2.7 on 2020-10-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201019_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'User Progress', 'verbose_name_plural': 'User progres'},
        ),
    ]
